import PolicySection from '@components/PolicySection';
import { SEO } from '@layout';
import {
  Box,
  Link,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  Typography,
} from '@mui/material';
import { FC } from 'react';
import QA from './components/QA';

const PrivacyPolicyPage: FC = () => (
  <>
    <SEO
      title="Privacy Policy"
      description="This Privacy Policy is meant to help you understand what information we collect, why we collect it, and how you can update, manage, export, and delete your information."
    />
    <Paper sx={{ p: 4, gap: 8, display: 'flex', flexDirection: 'column' }}>
      {/* Generated by https://app.termly.io/ */}
      <PolicySection>
        <Typography variant="h2" component="h1">
          Privacy Notice
        </Typography>
        <Typography>Last updated August 22, 2022</Typography>
        <Typography sx={{ mb: -6 }}>
          This privacy notice for Shinebrothers (&quot;Company,&quot;
          &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;), describes how and
          why we might collect, store, use, and/or share (&quot;process&quot;)
          your information when you use our services (&quot;Services&quot;),
          such as when you:
        </Typography>
        <ul>
          <li>
            Visit our website at{' '}
            <Link href="https://pokecardmaker.net">
              https://pokecardmaker.net
            </Link>
            , or any website of ours that links to this privacy notice
          </li>
          <li>
            Engage with us in other related ways, including any sales,
            marketing, or events
          </li>
        </ul>
        <Typography>
          Questions or concerns? Reading this privacy notice will help you
          understand your privacy rights and choices. If you do not agree with
          our policies and practices, please do not use our Services. If you
          still have any questions or concerns, please contact us at{' '}
          <Link href="mailto:info@shinebrothers.nl">info@shinebrothers.nl</Link>
          .
        </Typography>
      </PolicySection>
      <PolicySection title="Summary of key points">
        <Typography>
          This summary provides key points from our privacy notice, but you can
          find out more details about any of these topics by clicking the link
          following each key point or by using our table of contents below to
          find the section you are looking for. You can also click{' '}
          <Link href="#table-of-contents">here</Link> to go directly to our
          table of contents.
        </Typography>
        <QA
          q="What personal information do we process?"
          a={
            <Typography>
              When you visit, use, or navigate our Services, we may process
              personal information depending on how you interact with
              Shinebrothers and the Services, the choices you make, and the
              products and features you use. Click{' '}
              <Link href="#personal-info">here</Link> to learn more.
            </Typography>
          }
        />
        <QA
          q="Do we process any sensitive personal information?"
          a="We do not process sensitive personal information."
        />
        <QA
          q="Do we receive any information from third parties?"
          a="We do not receive any information from third parties."
        />
        <QA
          q="How do we process your information?"
          a="We process your information to provide, improve, and administer our Services, communicate with you, for security and fraud prevention, and to comply with law. We may also process your information for other purposes with your consent. We process your information only when we have a valid legal reason to do so. Click here to learn more."
        />
        <QA
          q="In what situations and with which parties do we share personal information?"
          a={
            <Typography>
              We may share information in specific situations and with specific
              third parties. Click <Link href="#who-share">here</Link> to learn
              more.
            </Typography>
          }
        />
        <QA
          q="How do we keep your information safe?"
          a={
            <Typography>
              We may share information in specific situations and with specific
              third parties. Click <Link href="#who-share">here</Link> to learn
              more. We have organizational and technical processes and
              procedures in place to protect your personal information. However,
              no electronic transmission over the internet or information
              storage technology can be guaranteed to be 100% secure, so we
              cannot promise or guarantee that hackers, cybercriminals, or other
              unauthorized third parties will not be able to defeat our security
              and improperly collect, access, steal, or modify your information.
              Click <Link href="#info-safe">here</Link> to learn more.
            </Typography>
          }
        />
        <QA
          q="What are your rights?"
          a={
            <Typography>
              Depending on where you are located geographically, the applicable
              privacy law may mean you have certain rights regarding your
              personal information. Click{' '}
              <Link href="#privacy-rights">here</Link> to learn more.
            </Typography>
          }
        />
        <QA
          q="How do you exercise your rights?"
          a={
            <Typography>
              Depending on where you are located geographically, the applicable
              privacy law may mean you have certain rights regarding your
              personal information. Click{' '}
              <Link href="#privacy-rights">here</Link> to learn more. The
              easiest way to exercise your rights is by filling e-mailing{' '}
              <Link href="mailto:info@shinebrothers.nl">
                info@shinebrothers.nl
              </Link>
              . We will consider and act upon any request in accordance with
              applicable data protection laws.
            </Typography>
          }
        />
      </PolicySection>
      <PolicySection title="Table of contents" id="table-of-contents">
        <Box mt={-3}>
          <ol>
            <li>
              <Link href="#info-collect">What information do we collect?</Link>
            </li>
            <li>
              <Link href="#info-use">How do we process your information?</Link>
            </li>
            <li>
              <Link href="#legal-bases">
                What legal bases do we rely on to process your personal
                information?
              </Link>
            </li>
            <li>
              <Link href="#who-share">
                When and with whom do we share your personal information?
              </Link>
            </li>
            <li>
              <Link href="#cookies">
                Do we use cookies and other tracking technologies?
              </Link>
            </li>
            <li>
              <Link href="#info-retain">
                How long do we keep your information?
              </Link>
            </li>
            <li>
              <Link href="#info-safe">
                How do we keep your information safe?
              </Link>
            </li>
            <li>
              <Link href="#privacy-rights">What are your privacy rights?</Link>
            </li>
            <li>
              <Link href="#dnt">Controls for do-not-track features</Link>
            </li>
            <li>
              <Link href="#ca-residents">
                Do California residents have specific privacy rights?
              </Link>
            </li>
            <li>
              <Link href="#policy-updates">
                Do we make updates to this notice?
              </Link>
            </li>
            <li>
              <Link href="#contact">
                How can you contact us about this notice?
              </Link>
            </li>
            <li>
              <Link href="#request">
                How can you review, update, or delete the data we collect from
                you?
              </Link>
            </li>
          </ol>
        </Box>
      </PolicySection>
      <PolicySection
        title="1. What information do we collect?"
        id="info-collect"
      >
        <Typography variant="h4">
          Personal information you disclose to us
        </Typography>
        <Typography fontStyle="italic">
          <b>In Short:</b> We collect personal information that you provide to
          us.
        </Typography>
        <Typography>
          We collect personal information that you voluntarily provide to us
          when you express an interest in obtaining information about us or our
          products and Services, when you participate in activities on the
          Services, or otherwise when you contact us.
        </Typography>
        <Typography>
          Sensitive Information. We do not process sensitive information.
        </Typography>
        <Typography>
          All personal information that you provide to us must be true,
          complete, and accurate, and you must notify us of any changes to such
          personal information.
        </Typography>
        <Typography variant="h4">
          Information automatically collected
        </Typography>
        <Typography fontStyle="italic">
          <b>In Short:</b> Some information — such as your Internet Protocol
          (IP) address and/or browser and device characteristics — is collected
          automatically when you visit our Services and consent to analytical
          statistics.
        </Typography>
        <Typography>
          We automatically collect certain information when you visit, use, or
          navigate the Services. This information does not reveal your specific
          identity (like your name or contact information) but may include
          device and usage information, such as your IP address, browser and
          device characteristics, operating system, language preferences,
          referring URLs, device name, country, location, information about how
          and when you use our Services, and other technical information. This
          information is primarily needed to maintain the security and operation
          of our Services, and for our internal analytics and reporting
          purposes.
        </Typography>
        <Typography>
          Like many businesses, we also collect information through cookies and
          similar technologies.
        </Typography>
        <Typography sx={{ mb: -6 }}>
          The information we collect includes:
        </Typography>
        <ul>
          <li>
            <i>Log and Usage Data.</i> Log and usage data is service-related,
            diagnostic, usage, and performance information our servers
            automatically collect when you access or use our Services and which
            we record in log files. Depending on how you interact with us, this
            log data may include your IP address, device information, browser
            type, and settings and information about your activity in the
            Services (such as the date/time stamps associated with your usage,
            pages and files viewed, searches, and other actions you take such as
            which features you use), device event information (such as system
            activity, error reports (sometimes called &quot;crash dumps&quot;),
            and hardware settings).
          </li>
          <li>
            <i>Device Data.</i> We collect device data such as information about
            your computer, phone, tablet, or other device you use to access the
            Services. Depending on the device used, this device data may include
            information such as your IP address (or proxy server), device and
            application identification numbers, location, browser type, hardware
            model, Internet service provider and/or mobile carrier, operating
            system, and system configuration information.
          </li>
          <li>
            <i>Location Data.</i> We collect location data such as information
            about your device&apos;s location, which can be either precise or
            imprecise. How much information we collect depends on the type and
            settings of the device you use to access the Services. For example,
            we may use GPS and other technologies to collect geolocation data
            that tells us your current location (based on your IP address). You
            can opt out of allowing us to collect this information either by
            refusing access to the information or by disabling your Location
            setting on your device. However, if you choose to opt out, you may
            not be able to use certain aspects of the Services.
          </li>
        </ul>
      </PolicySection>
      <PolicySection
        title="2. How do we process your information?"
        id="info-use"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> We process your information to provide, improve, and
          administer our Services, communicate with you, for security and fraud
          prevention, and to comply with law. We may also process your
          information for other purposes with your consent.
        </Typography>
        <Typography sx={{ mb: -6 }}>
          We process your personal information for a variety of reasons,
          depending on how you interact with our Services, including:
        </Typography>
        <ul>
          <li>
            <i>To identify usage trends.</i> We may process information about
            how you use our Services to better understand how they are being
            used so we can improve them.
          </li>
          <li>
            <i>To save or protect an individual&apos;s vital interest.</i> We
            may process your information when necessary to save or protect an
            individual&apos;s vital interest, such as to prevent harm.
          </li>
        </ul>
      </PolicySection>
      <PolicySection
        title="3. What legal bases do we rely on to process your personal information?"
        id="legal-bases"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> We only process your personal information when we
          believe it is necessary and we have a valid legal reason (i.e., legal
          basis) to do so under applicable law, like with your consent, to
          comply with laws, to provide you with services to enter into or
          fulfill our contractual obligations, to protect your rights, or to
          fulfill our legitimate business interests.
        </Typography>
        <Typography sx={{ textDecoration: 'underlined' }}>
          If you are located in the EU or UK, this section applies to you.
        </Typography>
        <Typography sx={{ mb: -6 }}>
          The General Data Protection Regulation (GDPR) and UK GDPR require us
          to explain the valid legal bases we rely on in order to process your
          personal information. As such, we may rely on the following legal
          bases to process your personal information:
        </Typography>
        <ul>
          <li>
            <i>Consent.</i> We may process your information if you have given us
            permission (i.e., consent) to use your personal information for a
            specific purpose. You can withdraw your consent at any time. Click{' '}
            <Link href="#withdraw-consent">here</Link> to learn more.
          </li>
          <li>
            <i>Legitimate Interests.</i>
            We may process your information when we believe it is reasonably
            necessary to achieve our legitimate business interests and those
            interests do not outweigh your interests and fundamental rights and
            freedoms. For example, we may process your personal information for
            some of the purposes described in order to analyze how our services
            are used so we can improve them to engage and retain users.
          </li>
          <li>
            <i>Legal Obligations.</i> We may process your information where we
            believe it is necessary for compliance with our legal obligations,
            such as to cooperate with a law enforcement body or regulatory
            agency, exercise or defend our legal rights, or disclose your
            information as evidence in litigation in which we are involved.
          </li>
          <li>
            <i>Vital Interests.</i> We may process your information where we
            believe it is necessary to protect your vital interests or the vital
            interests of a third party, such as situations involving potential
            threats to the safety of any person.
          </li>
        </ul>
        <Typography sx={{ textDecoration: 'underlined' }}>
          If you are located in Canada, this section applies to you.
        </Typography>
        <Typography>
          We may process your information if you have given us specific
          permission (i.e., express consent) to use your personal information
          for a specific purpose, or in situations where your permission can be
          inferred (i.e., implied consent). You can withdraw your consent at any
          time. Click <Link href="#withdraw-consent">here</Link> to learn more.
        </Typography>
        <Typography sx={{ mb: -6 }}>
          In some exceptional cases, we may be legally permitted under
          applicable law to process your information without your consent,
          including, for example:
        </Typography>
        <ul>
          <li>
            If collection is clearly in the interests of an individual and
            consent cannot be obtained in a timely way
          </li>
          <li>For investigations and fraud detection and prevention</li>
          <li>For business transactions provided certain conditions are met</li>
          <li>
            If it is contained in a witness statement and the collection is
            necessary to assess, process, or settle an insurance claim
          </li>
          <li>
            For identifying injured, ill, or deceased persons and communicating
            with next of kin
          </li>
          <li>
            If we have reasonable grounds to believe an individual has been, is,
            or may be victim of financial abuse
          </li>
          <li>
            If it is reasonable to expect collection and use with consent would
            compromise the availability or the accuracy of the information and
            the collection is reasonable for purposes related to investigating a
            breach of an agreement or a contravention of the laws of Canada or a
            province
          </li>
          <li>
            If disclosure is required to comply with a subpoena, warrant, court
            order, or rules of the court relating to the production of records
          </li>
          <li>
            If it was produced by an individual in the course of their
            employment, business, or profession and the collection is consistent
            with the purposes for which the information was produced
          </li>
          <li>
            If the collection is solely for journalistic, artistic, or literary
            purposes
          </li>
          <li>
            If the information is publicly available and is specified by the
            regulations
          </li>
        </ul>
      </PolicySection>
      <PolicySection
        title="4. When and with whom do we share your personal information?"
        id="who-share"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> We may share information in specific situations
          described in this section and/or with the following third parties.
        </Typography>
        <Typography sx={{ mb: -6 }}>
          <i>Vendors, Consultants, and Other Third-Party Service Providers.</i>{' '}
          We may share your data with third-party vendors, service providers,
          contractors, or agents (&quot;third parties&quot;) who perform
          services for us or on our behalf and require access to such
          information to do that work. We have contracts in place with our third
          parties, which are designed to help safeguard your personal
          information. This means that they cannot do anything with your
          personal information unless we have instructed them to do it. They
          will also not share your personal information with any organization
          apart from us. They also commit to protect the data they hold on our
          behalf and to retain it for the period we instruct. The third parties
          we may share personal information with are as follows:
        </Typography>
        <ul>
          <li>
            <b>Content Optimization:</b> Google Fonts
          </li>
          <li>
            <b>Web and Mobile Analytics:</b> Google Analytics and Google Tag
            Manager
          </li>
        </ul>
        <Typography sx={{ mb: -6 }}>
          We also may need to share your personal information in the following
          situations:
        </Typography>
        <ul>
          <li>
            <i>Business Transfers.</i> We may share or transfer your information
            in connection with, or during negotiations of, any merger, sale of
            company assets, financing, or acquisition of all or a portion of our
            business to another company.
          </li>
        </ul>
      </PolicySection>
      <PolicySection
        title="5. Do we use cookies and other tracking technologies?"
        id="cookies"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> We may use cookies and other tracking technologies to
          collect and store your information.
        </Typography>
        <Typography>
          We may use cookies and similar tracking technologies (like web beacons
          and pixels) to access or store information. Specific information about
          how we use such technologies and how you can refuse certain cookies is
          set out in our Cookie Notice.
        </Typography>
      </PolicySection>
      <PolicySection
        title="6. How long do we keep your information?"
        id="info-retain"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> We keep your information for as long as necessary to
          fulfill the purposes outlined in this privacy notice unless otherwise
          required by law.
        </Typography>
        <Typography>
          We will only keep your personal information for as long as it is
          necessary for the purposes set out in this privacy notice, unless a
          longer retention period is required or permitted by law (such as tax,
          accounting, or other legal requirements). No purpose in this notice
          will require us keeping your personal information for longer than 2
          years.
        </Typography>
        <Typography>
          When we have no ongoing legitimate business need to process your
          personal information, we will either delete or anonymize such
          information, or, if this is not possible (for example, because your
          personal information has been stored in backup archives), then we will
          securely store your personal information and isolate it from any
          further processing until deletion is possible.
        </Typography>
      </PolicySection>
      <PolicySection
        title="7. How do we keep your information safe?"
        id="info-safe"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> We aim to protect your personal information through a
          system of organizational and technical security measures.
        </Typography>
        <Typography>
          We have implemented appropriate and reasonable technical and
          organizational security measures designed to protect the security of
          any personal information we process. However, despite our safeguards
          and efforts to secure your information, no electronic transmission
          over the Internet or information storage technology can be guaranteed
          to be 100% secure, so we cannot promise or guarantee that hackers,
          cybercriminals, or other unauthorized third parties will not be able
          to defeat our security and improperly collect, access, steal, or
          modify your information. Although we will do our best to protect your
          personal information, transmission of personal information to and from
          our Services is at your own risk. You should only access the Services
          within a secure environment.
        </Typography>
      </PolicySection>
      <PolicySection
        title="8. What are your privacy rights?"
        id="privacy-rights"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> In some regions, such as the European Economic Area
          (EEA), United Kingdom (UK), and Canada, you have rights that allow you
          greater access to and control over your personal information. You may
          review, change, or terminate your account at any time.
        </Typography>
        <Typography>
          In some regions (like the EEA, UK, and Canada), you have certain
          rights under applicable data protection laws. These may include the
          right (i) to request access and obtain a copy of your personal
          information, (ii) to request rectification or erasure; (iii) to
          restrict the processing of your personal information; and (iv) if
          applicable, to data portability. In certain circumstances, you may
          also have the right to object to the processing of your personal
          information. You can make such a request by contacting us by using the
          contact details provided in the section{' '}
          <Link href="#contact">
            &quot;How can you contact us about this notice?&quot;
          </Link>{' '}
          below.
        </Typography>
        <Typography>
          We will consider and act upon any request in accordance with
          applicable data protection laws.
        </Typography>
        <Typography>
          If you are located in the EEA or UK and you believe we are unlawfully
          processing your personal information, you also have the right to
          complain to your local data protection supervisory authority. You can
          find their contact details here:{' '}
          <Link href="https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm">
            https://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm
          </Link>
          .
        </Typography>
        <Typography>
          If you are located in Switzerland, the contact details for the data
          protection authorities are available here:{' '}
          <Link href="https://www.edoeb.admin.ch/edoeb/en/home.html">
            https://www.edoeb.admin.ch/edoeb/en/home.html
          </Link>
          .
        </Typography>
        <Typography>
          <i id="withdraw-consent">Withdrawing your consent:</i> If we are
          relying on your consent to process your personal information, which
          may be express and/or implied consent depending on the applicable law,
          you have the right to withdraw your consent at any time. You can
          withdraw your consent at any time by contacting us by using the
          contact details provided in the section{' '}
          <Link href="#contact">
            &quot;How can you contact us about this notice?&quot;
          </Link>{' '}
          below.
        </Typography>
        <Typography>
          However, please note that this will not affect the lawfulness of the
          processing before its withdrawal nor, when applicable law allows, will
          it affect the processing of your personal information conducted in
          reliance on lawful processing grounds other than consent.
        </Typography>
        <Typography>
          <i>Cookies and similar technologies:</i> Most Web browsers are set to
          accept cookies by default. If you prefer, you can usually choose to
          set your browser to remove cookies and to reject cookies. If you
          choose to remove cookies or reject cookies, this could affect certain
          features or services of our Services. To opt out of interest-based
          advertising by advertisers on our Services visit{' '}
          <Link href="http://www.aboutads.info/choices/">
            http://www.aboutads.info/choices/
          </Link>
          .
        </Typography>
        <Typography>
          If you have questions or comments about your privacy rights, you may
          email us at{' '}
          <Link href="mailto:info@shinebrothers.nl">info@shinebrothers.nl</Link>
          .
        </Typography>
      </PolicySection>
      <PolicySection title="9. Controls for do-not-track features?" id="dnt">
        <Typography>
          Most web browsers and some mobile operating systems and mobile
          applications include a Do-Not-Track (&quot;DNT&quot;) feature or
          setting you can activate to signal your privacy preference not to have
          data about your online browsing activities monitored and collected. At
          this stage no uniform technology standard for recognizing and
          implementing DNT signals has been finalized. As such, we do not
          currently respond to DNT browser signals or any other mechanism that
          automatically communicates your choice not to be tracked online. If a
          standard for online tracking is adopted that we must follow in the
          future, we will inform you about that practice in a revised version of
          this privacy notice.
        </Typography>
      </PolicySection>
      <PolicySection
        title="10. Do California residents have specific privacy rights?"
        id="ca-residents"
      >
        <Typography fontStyle="italic">
          <b>In Short:</b> Yes, if you are a resident of California, you are
          granted specific rights regarding access to your personal information.
        </Typography>
        <Typography>
          California Civil Code Section 1798.83, also known as the &quot;Shine
          The Light&quot; law, permits our users who are California residents to
          request and obtain from us, once a year and free of charge,
          information about categories of personal information (if any) we
          disclosed to third parties for direct marketing purposes and the names
          and addresses of all third parties with which we shared personal
          information in the immediately preceding calendar year. If you are a
          California resident and would like to make such a request, please
          submit your request in writing to us using the contact information
          provided below.
        </Typography>
        <Typography>
          If you are under 18 years of age, reside in California, and have a
          registered account with Services, you have the right to request
          removal of unwanted data that you publicly post on the Services. To
          request removal of such data, please contact us using the contact
          information provided below and include the email address associated
          with your account and a statement that you reside in California. We
          will make sure the data is not publicly displayed on the Services, but
          please be aware that the data may not be completely or comprehensively
          removed from all our systems (e.g., backups, etc.).
        </Typography>
        <Typography variant="h4">CCPA Privacy notice</Typography>
        <Typography sx={{ mb: -6 }}>
          The California Code of Regulations defines a &quot;resident&quot; as:
        </Typography>
        <ul>
          <li>
            (1) every individual who is in the State of California for other
            than a temporary or transitory purpose and
          </li>
          <li>
            (2) every individual who is domiciled in the State of California who
            is outside the State of California for a temporary or transitory
            purpose
          </li>
        </ul>
        <Typography>
          All other individuals are defined as &quot;non-residents.&quot;
        </Typography>
        <Typography>
          If this definition of &quot;resident&quot; applies to you, we must
          adhere to certain rights and obligations regarding your personal
          information.
        </Typography>
        <Typography fontWeight="bold">
          What categories of personal information do we collect?
        </Typography>
        <Typography>
          We have collected the following categories of personal information in
          the past twelve (12) months:
        </Typography>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>Category</TableCell>
              <TableCell>Examples</TableCell>
              <TableCell>Collected</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            <TableRow>
              <TableCell>A. Identifiers</TableCell>
              <TableCell>
                Contact details, such as real name, alias, postal address,
                telephone or mobile contact number, unique personal identifier,
                online identifier, Internet Protocol address, email address, and
                account name
              </TableCell>
              <TableCell align="center">YES</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                B. Personal information categories listed in the California
                Customer Records statute
              </TableCell>
              <TableCell>
                Name, contact information, education, employment, employment
                history, and financial information
              </TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                C. Protected classification characteristics under California or
                federal law
              </TableCell>
              <TableCell>Gender and date of birth</TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>D. Commercial information</TableCell>
              <TableCell>
                Transaction information, purchase history, financial details,
                and payment information
              </TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>E. Biometric information</TableCell>
              <TableCell>Fingerprints and voiceprints</TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                F. Internet or other similar network activity
              </TableCell>
              <TableCell>
                Browsing history, search history, online behavior, interest
                data, and interactions with our and other websites,
                applications, systems, and advertisements
              </TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>G. Geolocation data</TableCell>
              <TableCell>Device location</TableCell>
              <TableCell align="center">YES</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                H. Audio, electronic, visual, thermal, olfactory, or similar
                information
              </TableCell>
              <TableCell>
                Images and audio, video or call recordings created in connection
                with our business activities
              </TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                I. Professional or employment-related information
              </TableCell>
              <TableCell>
                Business contact details in order to provide you our Services at
                a business level or job title, work history, and professional
                qualifications if you apply for a job with us
              </TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>J. Education Information</TableCell>
              <TableCell>Student records and directory information</TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
            <TableRow>
              <TableCell>
                K. Inferences drawn from other personal information
              </TableCell>
              <TableCell>
                Inferences drawn from any of the collected personal information
                listed above to create a profile or summary about, for example,
                an individual&apos;s preferences and characteristics
              </TableCell>
              <TableCell align="center">NO</TableCell>
            </TableRow>
          </TableBody>
        </Table>
        <Typography sx={{ mb: -6 }}>
          We may also collect other personal information outside of these
          categories through instances where you interact with us in person,
          online, or by phone or mail in the context of:
        </Typography>
        <ul>
          <li>Receiving help through our customer support channels;</li>
          <li>Participation in customer surveys or contests; and</li>
          <li>
            Facilitation in the delivery of our Services and to respond to your
            inquiries.
          </li>
        </ul>
        <Typography fontWeight="bold">
          How do we use and share your personal information?
        </Typography>
        <Typography>
          More information about our data collection and sharing practices can
          be found in this privacy notice.
        </Typography>
        <Typography>
          You may contact us by email at{' '}
          <Link href="mailto:info@shinebrothers.nl">info@shinebrothers.nl</Link>
          , or by referring to the contact details at the bottom of this
          document.
        </Typography>
        <Typography>
          If you are using an authorized agent to exercise your right to opt out
          we may deny a request if the authorized agent does not submit proof
          that they have been validly authorized to act on your behalf.
        </Typography>
        <Typography fontWeight="bold">
          Will your information be shared with anyone else?
        </Typography>
        <Typography>
          We may disclose your personal information with our service providers
          pursuant to a written contract between us and each service provider.
          Each service provider is a for-profit entity that processes the
          information on our behalf.
        </Typography>
        <Typography>
          We may use your personal information for our own business purposes,
          such as for undertaking internal research for technological
          development and demonstration. This is not considered to be
          &quot;selling&quot; of your personal information.
        </Typography>
        <Typography sx={{ mb: -6 }}>
          Shinebrothers has not sold any personal information to third parties
          for a business or commercial purpose in the preceding twelve (12)
          months. Shinebrothers has disclosed the following categories of
          personal information to third parties for a business or commercial
          purpose in the preceding twelve (12) months:
        </Typography>
        <ul>
          <li>
            Category A. Identifiers, such as contact details like your real
            name, alias, postal address, telephone or mobile contact number,
            unique personal identifier, online identifier, Internet Protocol
            address, email address, and account name.
          </li>
          <li>
            Category B. Personal Information, as defined in the California
            Customer Records law, such as your name, contact information,
            education, employment, employment history, and financial
            information.
          </li>
          <li>Category G. Geolocation data, such as device location.</li>
        </ul>
        <Typography>
          The categories of third parties to whom we disclosed personal
          information for a business or commercial purpose can be found under{' '}
          <Link href="#who-share">
            &quot;When and with whom do we share your personal
            information?&quot;
          </Link>
          .
        </Typography>
        <Typography fontWeight="bold">
          Your rights with respect to your personal data
        </Typography>
        <Typography sx={{ textDecoration: 'underline' }}>
          Right to request deletion of the data — Request to delete
        </Typography>
        <Typography>
          You can ask for the deletion of your personal information. If you ask
          us to delete your personal information, we will respect your request
          and delete your personal information, subject to certain exceptions
          provided by law, such as (but not limited to) the exercise by another
          consumer of his or her right to free speech, our compliance
          requirements resulting from a legal obligation, or any processing that
          may be required to protect against illegal activities.
        </Typography>
        <Typography sx={{ textDecoration: 'underline' }}>
          Right to be informed — Request to know
        </Typography>
        <Typography sx={{ mb: -6 }}>
          Depending on the circumstances, you have a right to know:
        </Typography>
        <ul>
          <li>whether we collect and use your personal information;</li>
          <li>the categories of personal information that we collect;</li>
          <li>
            the purposes for which the collected personal information is used;
          </li>
          <li>whether we sell your personal information to third parties;</li>
          <li>
            the categories of personal information that we sold or disclosed for
            a business purpose;
          </li>
          <li>
            the categories of third parties to whom the personal information was
            sold or disclosed for a business purpose; and
          </li>
          <li>
            the business or commercial purpose for collecting or selling
            personal information.
          </li>
        </ul>
        <Typography>
          In accordance with applicable law, we are not obligated to provide or
          delete consumer information that is de-identified in response to a
          consumer request or to re-identify individual data to verify a
          consumer request.
        </Typography>
        <Typography sx={{ textDecoration: 'underline' }}>
          Right to Non-Discrimination for the Exercise of a Consumer&apos;s
          Privacy Rights
        </Typography>

        <Typography>
          We will not discriminate against you if you exercise your privacy
          rights.
        </Typography>

        <Typography sx={{ textDecoration: 'underline' }}>
          Verification process
        </Typography>

        <Typography>
          Upon receiving your request, we will need to verify your identity to
          determine you are the same person about whom we have the information
          in our system. These verification efforts require us to ask you to
          provide information so that we can match it with information you have
          previously provided us. For instance, depending on the type of request
          you submit, we may ask you to provide certain information so that we
          can match the information you provide with the information we already
          have on file, or we may contact you through a communication method
          (e.g., phone or email) that you have previously provided to us. We may
          also use other verification methods as the circumstances dictate.
        </Typography>
        <Typography>
          We will only use personal information provided in your request to
          verify your identity or authority to make the request. To the extent
          possible, we will avoid requesting additional information from you for
          the purposes of verification. However, if we cannot verify your
          identity from the information already maintained by us, we may request
          that you provide additional information for the purposes of verifying
          your identity and for security or fraud-prevention purposes. We will
          delete such additionally provided information as soon as we finish
          verifying you.
        </Typography>

        <Typography sx={{ textDecoration: 'underline', mb: -6 }}>
          Other privacy rights
        </Typography>
        <ul>
          <li>
            You may object to the processing of your personal information.
          </li>
          <li>
            You may request correction of your personal data if it is incorrect
            or no longer relevant, or ask to restrict the processing of the
            information.
          </li>
          <li>
            You can designate an authorized agent to make a request under the
            CCPA on your behalf. We may deny a request from an authorized agent
            that does not submit proof that they have been validly authorized to
            act on your behalf in accordance with the CCPA.
          </li>
          <li>
            You may request to opt out from future selling of your personal
            information to third parties. Upon receiving an opt-out request, we
            will act upon the request as soon as feasibly possible, but no later
            than fifteen (15) days from the date of the request submission.
          </li>
        </ul>
        <Typography>
          To exercise these rights, you can contact us by email at
          leonvdnoll@gmail.com, or by referring to the contact details at the
          bottom of this document. If you have a complaint about how we handle
          your data, we would like to hear from you.
        </Typography>
      </PolicySection>
      <PolicySection
        title="11. Do we make updates to this notice?"
        id="policy-updates"
      >
        <Typography>
          <Typography fontStyle="italic">
            <b>In Short:</b> Yes, we will update this notice as necessary to
            stay compliant with relevant laws.
          </Typography>
          <Typography>
            We may update this privacy notice from time to time. The updated
            version will be indicated by an updated &quot;Revised&quot; date and
            the updated version will be effective as soon as it is accessible.
            If we make material changes to this privacy notice, we may notify
            you either by prominently posting a notice of such changes or by
            directly sending you a notification. We encourage you to review this
            privacy notice frequently to be informed of how we are protecting
            your information.
          </Typography>
        </Typography>
      </PolicySection>
      <PolicySection
        title="12. How can you contact us about this notice?"
        id="contact"
      >
        <Typography>
          If you have questions or comments about this notice, you may email us
          at{' '}
          <Link href="mailto:info@shinebrothers.nl">info@shinebrothers.nl</Link>
          .
        </Typography>
      </PolicySection>
      <PolicySection
        title="13. How can you review, update, or delete the data we collect from you?"
        id="request"
      >
        <Typography>
          Based on the applicable laws of your country, you may have the right
          to request access to the personal information we collect from you,
          change that information, or delete it. To request to review, update,
          or delete your personal information, please e-mail us at:{' '}
          <Link href="mailto:info@shinebrothers.nl">info@shinebrothers.nl</Link>
          .
        </Typography>
      </PolicySection>
    </Paper>
  </>
);

export default PrivacyPolicyPage;
