import PolicySection from '@components/PolicySection';
import { SEO } from '@layout';
import { Link, Paper, Typography } from '@mui/material';
import Routes from '@routes';
import { FC } from 'react';
import CookieTable from './components/CookieTable';

const CookiePolicyPage: FC = () => (
  <>
    <SEO
      title="Cookie Policy"
      description="This page describes the types of cookies and other technologies used by us."
    />
    <Paper sx={{ p: 4, gap: 8, display: 'flex', flexDirection: 'column' }}>
      {/* Generated by https://app.termly.io/ */}
      <PolicySection>
        <Typography variant="h2" component="h1">
          Cookie Policy
        </Typography>
        <Typography>Last updated September 08, 2022</Typography>
        <Typography>
          This Cookie Policy explains how Shinebrothers (&quot;Company&quot;,
          &quot;we&quot;, &quot;us&quot;, and &quot;our&quot;) uses cookies and
          similar technologies to recognize you when you visit our websites at{' '}
          <Link href="https://pokecardmaker.net">
            https://pokecardmaker.net
          </Link>
          , (&quot;Websites&quot;). It explains what these technologies are and
          why we use them, as well as your rights to control our use of them.
        </Typography>
        <Typography>
          In some cases we may use cookies to collect personal information, or
          that becomes personal information if we combine it with other
          information.
        </Typography>
      </PolicySection>
      <PolicySection title="What are cookies?">
        <Typography>
          Cookies are small data files that are placed on your computer or
          mobile device when you visit a website. Cookies are widely used by
          website owners in order to make their websites work, or to work more
          efficiently, as well as to provide reporting information.
        </Typography>
        <Typography>
          Cookies set by the website owner (in this case, Shinebrothers) are
          called &quot;first party cookies&quot;. Cookies set by parties other
          than the website owner are called &quot;third party cookies&quot;.
          Third party cookies enable third party features or functionality to be
          provided on or through the website (e.g. like advertising, interactive
          content and analytics). The parties that set these third party cookies
          can recognize your computer both when it visits the website in
          question and also when it visits certain other websites.
        </Typography>
      </PolicySection>
      <PolicySection title="Why do we use cookies?">
        <Typography>
          We use first and third party cookies for several reasons. Some cookies
          are required for technical reasons in order for our Websites to
          operate, and we refer to these as &quot;essential&quot; or
          &quot;strictly necessary&quot; cookies. Other cookies also enable us
          to track and target the interests of our users to enhance the
          experience on our Online Properties. Third parties serve cookies
          through our Websites for advertising, analytics and other purposes.
          This is described in more detail below.
        </Typography>
        <Typography>
          The specific types of first and third party cookies served through our
          Websites and the purposes they perform are described below (please
          note that the specific cookies served may vary depending on the
          specific Online Properties you visit):
        </Typography>
      </PolicySection>
      <PolicySection title="How can I control cookies?">
        <Typography>
          You have the right to decide whether to accept or reject cookies. You
          can exercise your cookie rights by setting your preferences in the
          Cookie Consent Manager. The Cookie Consent Manager allows you to
          select which categories of cookies you accept or reject. Essential
          cookies cannot be rejected as they are strictly necessary to provide
          you with services.
        </Typography>
        <Typography>
          The Cookie Consent Manager can be found in the notification banner and
          on our website. If you choose to reject cookies, you may still use our
          website though your access to some functionality and areas of our
          website may be restricted. You may also set or amend your web browser
          controls to accept or refuse cookies. As the means by which you can
          refuse cookies through your web browser controls vary from
          browser-to-browser, you should visit your browser&apos;s help menu for
          more information.
        </Typography>
        <Typography>
          In addition, most advertising networks offer you a way to opt out of
          targeted advertising. If you would like to find out more information,
          please visit{' '}
          <Link href="http://www.aboutads.info/choices/">
            http://www.aboutads.info/choices/
          </Link>{' '}
          or{' '}
          <Link href="http://www.youronlinechoices.com">
            http://www.youronlinechoices.com
          </Link>
          .
        </Typography>
        <Typography>
          The specific types of first and third party cookies served through our
          Websites and the purposes they perform are described in the table
          below (please note that the specific cookies served may vary depending
          on the specific Online Properties you visit):
        </Typography>
      </PolicySection>
      <PolicySection title="Performance and functionality cookies">
        <Typography>
          These cookies are used to enhance the performance and functionality of
          our Websites but are non-essential to their use. However, without
          these cookies, certain functionality (like videos) may become
          unavailable.
        </Typography>
        <CookieTable
          name="analytics_consent"
          purpose="Keeps track of whether you consented to using cookies on this website."
          service="Pokécardmaker"
          serviceUrl={Routes.PrivacyPolicy}
        />
      </PolicySection>
      <PolicySection title="Analytics and customization cookies">
        <Typography>
          These cookies collect information that is used either in aggregate
          form to help us understand how our Websites are being used or how
          effective our marketing campaigns are, or to help us customize our
          Websites for you.
        </Typography>
        <CookieTable
          name="_ga"
          purpose="It records a particular ID used to come up with data about website usage by the user. It is a HTTP cookie that expires after 2 years."
          service="Google Analytics"
          serviceUrl="https://policies.google.com/technologies/ads"
          expiration="2 years"
        />
        <CookieTable
          name="_ga_P9YVYCP24K"
          purpose="It records a particular ID used to come up with data about website usage by the user. It is a HTTP cookie that expires after 2 years."
          service="Google Analytics"
          serviceUrl="https://policies.google.com/technologies/ads"
          expiration="2 years"
        />
      </PolicySection>
      <PolicySection title="What about other tracking technologies, like web beacons?">
        <Typography>We do not use web beacons or tracking pixels.</Typography>
        <Typography>
          Cookies are not the only way to recognize or track visitors to a
          website. Similar technologies, like web beacons (sometimes called
          &quot;tracking pixels&quot; or &quot;clear gifs&quot;) exist. These
          are tiny graphics files that contain a unique identifier that enable
          us to recognize when someone has visited our Websites or opened an
          e-mail including them. This allows us, for example, to monitor the
          traffic patterns of users from one page within a website to another,
          to deliver or communicate with cookies, to understand whether you have
          come to the website from an online advertisement displayed on a
          third-party website, to improve site performance, and to measure the
          success of e-mail marketing campaigns. In many instances, these
          technologies are reliant on cookies to function properly, and so
          declining cookies will impair their functioning.
        </Typography>
      </PolicySection>
      <PolicySection title="Do you use Flash cookies or Local Shared Objects?">
        <Typography>
          Websites may also use so-called &quot;Flash Cookies&quot; (also known
          as Local Shared Objects or &quot;LSOs&quot;) to, among other things,
          collect and store information about your use of our services, fraud
          prevention and for other site operations.
        </Typography>
        <Typography>
          If you do not want Flash Cookies stored on your computer, you can
          adjust the settings of your Flash player to block Flash Cookies
          storage using the tools contained in the{' '}
          <Link href="http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html">
            Website Storage Settings Panel
          </Link>
          . You can also control Flash Cookies by going to the{' '}
          <Link href="http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager03.html">
            Global Storage Settings Panel
          </Link>{' '}
          and following the instructions (which may include instructions that
          explain, for example, how to delete existing Flash Cookies (referred
          to &quot;information&quot; on the Macromedia site), how to prevent
          Flash LSOs from being placed on your computer without your being
          asked, and (for Flash Player 8 and later) how to block Flash Cookies
          that are not being delivered by the operator of the page you are on at
          the time).
        </Typography>
        <Typography>
          Please note that setting the Flash Player to restrict or limit
          acceptance of Flash Cookies may reduce or impede the functionality of
          some Flash applications.
        </Typography>
      </PolicySection>
      <PolicySection title="Do you serve targeted advertising?">
        {/* <Typography>
          Third parties may serve cookies on your computer or mobile device to
          serve advertising through our Websites. These companies may use
          information about your visits to this and other websites in order to
          provide relevant advertisements about goods and services that you may
          be interested in. They may also employ technology that is used to
          measure the effectiveness of advertisements. This can be accomplished
          by them using cookies or web beacons to collect information about your
          visits to this and other sites in order to provide relevant
          advertisements about goods and services of potential interest to you.
          The information collected through this process does not enable us or
          them to identify your name, contact details or other details that
          directly identify you unless you choose to provide these.
        </Typography> */}
        <Typography>
          No, there are no advertisements on this website at this moment.
        </Typography>
      </PolicySection>
      <PolicySection title="How often will you update this Cookie Policy?">
        <Typography>
          We may update this Cookie Policy from time to time in order to
          reflect, for example, changes to the cookies we use or for other
          operational, legal or regulatory reasons. Please therefore re-visit
          this Cookie Policy regularly to stay informed about our use of cookies
          and related technologies.
        </Typography>
        <Typography>
          The date at the top of this Cookie Policy indicates when it was last
          updated.
        </Typography>
      </PolicySection>
      <PolicySection title="Where can I get further information?">
        <Typography>
          If you have any questions about our use of cookies or other
          technologies, please email us at{' '}
          <Link href="mailto:info@shinebrothers.nl">info@shinebrothers.nl</Link>
          .
        </Typography>
      </PolicySection>
    </Paper>
  </>
);

export default CookiePolicyPage;
